apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
configMapGenerator:
- behavior: replace
  literals:
  - my-configmap-file=I am a development environment
  name: my-cm
