apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
configMapGenerator:
- behavior: replace
  literals:
  - my-configmap-file=I am a production environment [edited!]
  name: my-cm
namespace: prod
patches:
- path: settings.yaml
