apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- my-it.yaml
configMapGenerator:
- behavior: create
  literals:
  - my-configmap-file=I am a default environment
  name: my-cm
  options:
    disableNameSuffixHash: true
