apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  annotations:
    camel.apache.org/operator.id: camel-k
  creationTimestamp: null
  name: my-route
spec:
  flows:
  - from:
      parameters:
        period: "1000"
      steps:
      - setBody:
          simple: resource:classpath:my-configmap-file
      - to: log:info
      uri: timer:yaml
  traits:
    container:
      limitCPU: "0.1"
      limitMemory: 256Mi
    mount:
      configs:
      - configmap:my-cm
status: {}
